name: payu_in_web
description: "Web implementation of PayU Payment Gateway. Launch with all options enabled or directly into an enforced payment flow."
version: 1.0.1
homepage: https://github.com/uncoded-decimal/payu_in_web

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: